language: ruby

rvm:
  - ruby-2.3.0

sudo: required

services:
  - postgres

branches:
  only:
    - master

cache: yarn

before_install:
  - export TZ=America/New_York

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.11.0
  - nvm use 8.11.0
  - bundle install --retry=3
  - yarn install

script:
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/student_insights_test
  - bundle exec rake immigrant:check_keys
  - ./scripts/ci/detect_package_lock.sh
  - rubocop
  - bundle exec rspec spec
  - yarn test-cli
