language: ruby

cache:
  bundler: true
  yarn: true

rvm:
  - ruby-2.5.3

sudo: required

services:
  - postgres

branches:
  only:
    - master

before_install:
  - export TZ=America/New_York
  - curl -o- -L https://yarnpkg.com/install.sh | bash # see https://github.com/travis-ci/travis-ci/issues/7471#issuecomment-288832948

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install --lts
  - nvm use --lts
  - bundle install --retry=3
  - yarn install

script:
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/student_insights_test
  - bundle exec rake immigrant:check_keys
  - ./scripts/ci/detect_package_lock.sh
  - rubocop
  - bundle exec brakeman -z
  - bundle exec rspec spec
  - yarn test-cli
