remote_filenames:
  # SIS data
  FILENAME_FOR_EDUCATORS_IMPORT:                    /home/jbreslin/data/educators_export.txt
  FILENAME_FOR_STUDENTS_IMPORT:                     /home/jbreslin/data/students_export.txt
  FILENAME_FOR_BEHAVIOR_IMPORT:                     /home/jbreslin/data/behavior_export.txt
  FILENAME_FOR_ASSESSMENT_IMPORT:                   /home/jbreslin/data/assessment_export.txt
  FILENAME_FOR_ATTENDANCE_IMPORT:                   /home/jbreslin/data/attendance_export.txt
  FILENAME_FOR_STUDENT_AVERAGES_IMPORT:             /home/jbreslin/data/student_averages_export.txt
  FILENAME_FOR_COURSE_SECTION_IMPORT:               /home/jbreslin/data/courses_sections_export.txt
  FILENAME_FOR_STUDENTS_SECTION_ASSIGNMENT_IMPORT:  /home/jbreslin/data/student_section_assignment_export.txt
  FILENAME_FOR_EDUCATOR_SECTION_ASSIGNMENT_IMPORT:  /home/jbreslin/data/educator_section_assignment_export.txt
  
  # student photos, one-time batch
  FILENAME_FOR_PHOTOS_ZIP:                          /home/jbreslin/data/photos.zip

  # iep at a glance PDFs
  FILENAMES_FOR_IEP_PDF_ZIPS:   # order is important here, these need to be oldest > newest
    - /home/jbreslin/data/student-documents-6.zip
    - /home/jbreslin/data/student-documents-5.zip
    - /home/jbreslin/data/student-documents-4.zip
    - /home/jbreslin/data/student-documents-3.zip
    - /home/jbreslin/data/student-documents-2.zip
    - /home/jbreslin/data/student-documents-1.zip

  # These are for STAR
  FILENAME_FOR_STAR_READING_IMPORT:                 SR.csv
  FILENAME_FOR_STAR_MATH_IMPORT:                    SM.csv
  FILENAME_FOR_STAR_ZIP_FILE:                       Somerville Public Schools.zip

school_definitions:
  - local_id: BRN
    name: Benjamin G Brown
    grades: K-5

  - local_id: HEA
    name: Arthur D Healey
    grades: K-8

  - local_id: KDY
    name: John F Kennedy
    grades: K-8

  - local_id: AFAS
    name: Albert F. Argenziano School
    grades: K-8

  - local_id: ESCS
    name: E Somerville Community
    grades: K-8

  - local_id: WSNS
    name: West Somerville Neighborhood
    grades: KF-8

  - local_id: WHCS
    name: Winter Hill Community
    grades: K-8

  - local_id: NW
    name: Next Wave Junior High
    grades: 7-8

  - local_id: SHS
    name: Somerville High
    grades: 9-12
    school_type: HS

  - local_id: FC
    name: Full Circle High School
    grades: 9-12
    school_type: HS

  - local_id: CAP
    name: Capuano Early Childhood Center
    grades: PK
    school_type: EC

  - local_id: PIC
    name: Parent Information Center

  - local_id: SPED
    name: Special Education

  - local_id: CUM
    name: Cummings School
    skip_import: true

  - local_id: PHCS
    name: Powerhouse Community School
    skip_import: true

  - local_id: SCALE
    name: Somerville Center for Adult Learning Experiences
    skip_import: true

  - local_id: HIST
    name: (Historical, marker for students who have graduated, withdrawn, etc.)
    skip_import: true
